"""
RAG Service for WATT-IF.

Orchestrates retrieval from the ChromaDB vector store and natural-language
generation via Ollama (qwen3:8b) to answer user questions about electricity
forecasts.

Design doc reference: Component 5 — RAG Service.
Requirements: 6.1 – 6.10.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Generator

import httpx

from pipeline.models import ForecastDocument, ForecastMetadata
from storage.eda_store import EDAStore
from storage.vector_store import VectorStore, VectorStoreError

logger = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────

OLLAMA_URL = "http://localhost:11434/api/chat"
OLLAMA_MODEL = "qwen3:1.7b"
OLLAMA_TEMPERATURE = 0.1
OLLAMA_TIMEOUT_SECONDS = 60.0
OLLAMA_NUM_PREDICT = 1024     # more headroom for explanatory answers
RETRIEVAL_TOP_K = 4
EDA_TOP_K = 3

_SYSTEM_PROMPT = """\
You are WATT-IF, a friendly electricity bill assistant for Filipino households.

Answer questions about electricity forecasts and bills in plain, simple language that any household member can understand. Avoid jargon. Be direct and conversational — like you are explaining to a friend, not writing a report.

RULES:
1. Only use information from the Forecast Data and Historical Data Analysis provided. Do not make up numbers.
2. If the data is not enough to answer, say so honestly.
3. Keep answers short unless the question needs more detail.

WHEN THE USER ASKS A SIMPLE QUESTION (like "how much", "what will my bill be", "show me the forecast"):
- Just answer directly. Give the number, a one-line reason if obvious, and that's it.

WHEN THE USER ASKS WHY, HOW, OR FOR AN EXPLANATION:
- Start with the short answer.
- Then explain the main reason in everyday terms. For example:
  - "It's hotter this month, so more fans and aircon use."
  - "The Meralco rate went up, so the bill is higher even if you used the same amount."
  - "El Niño means drier and hotter weather, which usually pushes up electricity use."
  - "More holidays mean more time at home, which can increase usage."
  - "More rainy days usually mean cooler weather and lower electricity use."
- If historical data is available, add a simple comparison like "Historically, this month tends to be one of the highest."
- Do not list every variable. Only mention the ones that are actually relevant for this specific question based on the data.

FORMATTING:
- Use short sentences.
- Use bullet points only when listing multiple items.
- Bold (**) key numbers like kWh and peso amounts.
- Do not use section headers like "Key Drivers" or "Historical Context" — just write naturally.

/no_think
"""

# User turn template — EDA section only included when relevant (see _needs_eda).
_USER_TEMPLATE = """\
Forecast Data:
{context_documents}{eda_section}

Question: {question}\
"""

_EDA_SECTION = """

Historical Data:
{eda_context}"""


# ── Response model ────────────────────────────────────────────────────────────


@dataclass
class RAGResponse:
    """Result returned by :meth:`RAGService.answer`.

    Attributes
    ----------
    answer:
        Natural-language answer generated by the LLM (or an error / fallback
        message when the LLM could not be reached or no documents exist).
    sources:
        List of :class:`~pipeline.models.ForecastMetadata` objects whose
        documents were passed as context to the LLM.  Empty when the LLM was
        not invoked (zero documents, retrieval error, timeout).
    error:
        ``True`` when the response represents an error condition rather than a
        successful LLM generation.
    """

    answer: str
    sources: list[ForecastMetadata] = field(default_factory=list)
    error: bool = False


# ── RAG Service ───────────────────────────────────────────────────────────────


class RAGService:
    """Retrieval-Augmented Generation service for WATT-IF.

    Parameters
    ----------
    vector_store:
        A :class:`~storage.vector_store.VectorStore` instance to retrieve
        forecast documents from.  If *None*, a default persistent store is
        created at the standard ChromaDB path.
    eda_store:
        A :class:`~storage.eda_store.EDAStore` instance to retrieve historical
        EDA context from.  If *None*, a default persistent store is created.
    """

    def __init__(
        self,
        vector_store: VectorStore | None = None,
        eda_store: EDAStore | None = None,
    ) -> None:
        self._vector_store: VectorStore = vector_store or VectorStore()
        self._eda_store: EDAStore = eda_store or EDAStore()

    # ── Private helpers ───────────────────────────────────────────────────────

    @staticmethod
    def _format_context(docs: list[ForecastDocument]) -> str:
        """Serialise *docs* into numbered context lines for the prompt."""
        lines: list[str] = []
        for i, doc in enumerate(docs, start=1):
            lines.append(f"[{i}] {doc.text}")
        return "\n".join(lines)

    @staticmethod
    def _format_eda_context(eda_docs: list[str]) -> str:
        """Serialise EDA summary texts into numbered context lines."""
        if not eda_docs:
            return "(No historical dataset analysis available.)"
        return "\n".join(f"[EDA-{i}] {text}" for i, text in enumerate(eda_docs, start=1))

    @staticmethod
    def _strip_think_blocks(text: str) -> str:
        """Remove all <think>…</think> blocks from *text*.

        Handles multiple blocks, nested content, and partial blocks where the
        closing tag is missing (strips from the opening tag to end of string).
        """
        import re
        # Remove complete blocks (non-greedy so multiple blocks work)
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
        # Remove any unclosed opening tag and everything after it
        text = re.sub(r"<think>.*", "", text, flags=re.DOTALL)
        return text.strip()

    @staticmethod
    def _needs_eda(question: str) -> bool:
        """Return True if the question is explanation-oriented or asks about historical trends.

        This covers both direct historical queries ("what's the average?") and
        causal/explanatory questions ("why is my bill high?", "how does El Niño
        affect usage?") that benefit from grounding in historical EDA summaries.
        """
        q = question.lower()
        keywords = [
            # Explicit historical / trend
            "historical", "past", "trend", "average", "highest", "lowest",
            "dataset", "previous", "before", "used to", "over the years",
            "history",
            # Explanatory / causal
            "why", "how", "explain", "reason", "because", "cause", "what causes",
            "what affects", "what drives", "what influences", "what impacts",
            "due to", "result of", "effect", "impact", "influence", "affect",
            # Comparison
            "compare", "comparison", "difference", "vs", "versus", "than",
            "more expensive", "cheaper", "higher", "lower", "increase", "decrease",
            "went up", "went down", "rise", "fall", "change",
            # Climate / exogenous variables
            "temperature", "rainfall", "humidity", "el nino", "el niño",
            "holiday", "hot days", "rainy days", "season", "summer", "dry",
            "meralco rate", "rate",
        ]
        return any(k in q for k in keywords)

    @staticmethod
    def _is_in_scope(question: str) -> bool:
        """Return True if the question is related to electricity bills or forecasts.

        Any question that doesn't touch electricity, energy, bills, consumption,
        forecasts, or costs is considered out of scope and will be rejected
        before reaching Ollama — saving tokens and blocking prompt injection.
        """
        q = question.lower()

        # Explicit out-of-scope topics — reject immediately regardless of other words
        out_of_scope = [
            "recipe", "cook", "food", "restaurant", "weather", "sport", "football",
            "basketball", "movie", "music", "song", "celebrity", "politics",
            "stock", "crypto", "bitcoin", "investment", "loan", "mortgage",
            "medical", "doctor", "health", "symptom", "disease", "vaccine",
            "legal", "lawyer", "law", "court", "insurance",
            "travel", "hotel", "flight", "visa",
            "ignore", "forget", "pretend", "act as", "jailbreak", "override",
            "system prompt", "instruction", "you are now", "disregard",
        ]
        if any(t in q for t in out_of_scope):
            return False

        # Must contain at least one in-scope keyword to pass
        in_scope = [
            "electricity", "electric", "bill", "bills", "kwh", "kilowatt",
            "consumption", "usage", "energy", "power", "forecast", "predict",
            "cost", "price", "peso", "spend", "spending", "monthly", "month",
            "watt", "watt-if", "wattif", "january", "february", "march",
            "april", "may", "june", "july", "august", "september", "october",
            "november", "december", "2020", "2021", "2022", "2023", "2024",
            "2025", "2026", "trend", "average", "historical", "past", "high",
            "low", "highest", "lowest", "season", "summer", "winter",
            "meralco", "rate", "temperature", "rainfall", "humidity",
            "el nino", "el niño", "holiday", "hot days", "rainy days",
            "weekend", "hot", "rainy",
        ]
        return any(k in q for k in in_scope)

    @staticmethod
    def _build_messages(
        question: str,
        docs: list[ForecastDocument],
        eda_docs: list[str],
    ) -> list[dict]:
        """Return the Ollama messages list with a system prompt and user turn."""
        context = RAGService._format_context(docs)
        eda_section = (
            _EDA_SECTION.format(eda_context=RAGService._format_eda_context(eda_docs))
            if eda_docs else ""
        )
        user_content = _USER_TEMPLATE.format(
            context_documents=context,
            eda_section=eda_section,
            question=question,
        )
        return [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user",   "content": user_content},
        ]

    def _retrieve(
        self, question: str
    ) -> tuple[list[ForecastDocument], list[str]] | RAGResponse:
        """Retrieve forecast docs and EDA docs for *question*.

        Returns a (docs, eda_docs) tuple on success, or a :class:`RAGResponse`
        error object if retrieval fails, yields nothing, or the question is
        outside the scope of WATT-IF.
        """
        # ── Scope guard — respond with a friendly out-of-scope message ─────────
        if not self._is_in_scope(question):
            logger.info("Out-of-scope question received: %r", question[:120])
            return RAGResponse(
                answer=(
                    "I'm sorry, but that question is outside the scope of WATT-IF. "
                    "This system is designed to help you with your household electricity bills, "
                    "energy consumption, and forecasts only. "
                    "Feel free to ask me anything about your electricity usage or upcoming bills!"
                ),
                sources=[],
                error=False,
            )
        try:
            docs = self._vector_store.query(question, top_k=RETRIEVAL_TOP_K)
        except (VectorStoreError, Exception) as exc:
            logger.error("Vector store retrieval failed: %s", exc, exc_info=True)
            return RAGResponse(
                answer=(
                    "Forecast retrieval failed. The vector store is currently "
                    "unavailable. Please try again later."
                ),
                sources=[],
                error=True,
            )

        eda_docs: list[str] = []
        try:
            if self._needs_eda(question):
                eda_docs = self._eda_store.query(question, top_k=EDA_TOP_K)
        except Exception as exc:
            logger.warning("EDA store retrieval failed (non-fatal): %s", exc)

        if not docs and not eda_docs:
            logger.info("No forecast or EDA documents found for query.")
            return RAGResponse(
                answer=(
                    "No forecast data is currently available to answer your question. "
                    "Please generate a forecast first."
                ),
                sources=[],
                error=False,
            )

        return docs, eda_docs

    # ── Public interface ──────────────────────────────────────────────────────

    def answer(self, question: str) -> RAGResponse:
        """Answer *question* using RAG (non-streaming).

        Kept for backward-compatibility and testing.  Prefer
        :meth:`stream_answer` for production use.
        """
        retrieved = self._retrieve(question)
        if isinstance(retrieved, RAGResponse):
            return retrieved
        docs, eda_docs = retrieved
        sources = [doc.metadata for doc in docs]
        messages = self._build_messages(question, docs, eda_docs)

        payload = {
            "model": OLLAMA_MODEL,
            "messages": messages,
            "stream": False,
            "keep_alive": -1,
            "think": False,
            "options": {
                "temperature": OLLAMA_TEMPERATURE,
                "num_predict": OLLAMA_NUM_PREDICT,
                "num_ctx": 4096,
            },
        }

        try:
            with httpx.Client(timeout=OLLAMA_TIMEOUT_SECONDS) as client:
                response = client.post(OLLAMA_URL, json=payload)
                response.raise_for_status()
                data = response.json()
        except httpx.TimeoutException as exc:
            logger.error("Ollama request timed out: %s", exc)
            return RAGResponse(
                answer=(
                    "The language model took too long to respond. "
                    "Please wait 30 seconds and try again."
                ),
                sources=sources,
                error=True,
            )
        except httpx.ConnectError as exc:
            logger.error("Ollama is unreachable: %s", exc)
            return RAGResponse(
                answer=(
                    "The LLM service (Ollama) is currently unavailable. "
                    "Please ensure Ollama is running on localhost:11434 and try again."
                ),
                sources=[],
                error=True,
            )
        except httpx.HTTPStatusError as exc:
            logger.error("Ollama returned HTTP %s: %s", exc.response.status_code, exc)
            return RAGResponse(
                answer=(
                    f"The LLM service returned an unexpected error "
                    f"(HTTP {exc.response.status_code}). Please try again later."
                ),
                sources=sources,
                error=True,
            )
        except Exception as exc:
            logger.error("Unexpected error calling Ollama: %s", exc, exc_info=True)
            return RAGResponse(
                answer="An unexpected error occurred while contacting the LLM service.",
                sources=sources,
                error=True,
            )

        try:
            answer_text: str = data["message"]["content"]
        except (KeyError, TypeError) as exc:
            logger.error("Unexpected Ollama response structure: %s", exc)
            return RAGResponse(
                answer="The LLM service returned an unexpected response format.",
                sources=sources,
                error=True,
            )

        return RAGResponse(answer=answer_text, sources=sources, error=False)

    def stream_answer(
        self, question: str
    ) -> Generator[str, None, None]:
        """Yield Server-Sent Events for *question* using true token-by-token streaming.

        Tokens are forwarded to the client as they arrive from Ollama.
        <think>…</think> blocks are stripped via a running buffer so the
        client never sees reasoning tokens, regardless of how they are chunked.

        Each yielded string is a complete SSE line::

            data: {"type": "token",  "text": "<chunk>"}
            data: {"type": "done",   "sources": [...]}
            data: {"type": "error",  "text": "<message>"}
        """
        import json

        retrieved = self._retrieve(question)
        if isinstance(retrieved, RAGResponse):
            # Out-of-scope or retrieval error — stream the canned message
            # token-by-token so it appears with the same typewriter effect.
            if retrieved.error:
                # Hard errors go out as a single error event
                yield f"data: {json.dumps({'type': 'error', 'text': retrieved.answer, 'sources': []})}\n\n"
            else:
                # Friendly out-of-scope / no-data message — stream it naturally
                CHUNK_SIZE = 4
                text = retrieved.answer
                for i in range(0, len(text), CHUNK_SIZE):
                    yield f"data: {json.dumps({'type': 'token', 'text': text[i:i + CHUNK_SIZE]})}\n\n"
                yield f"data: {json.dumps({'type': 'done', 'sources': []})}\n\n"
            return

        docs, eda_docs = retrieved
        sources = [
            {
                "forecast_month": m.forecast_month,
                "forecasted_kwh": m.forecasted_kwh,
                "forecasted_price": m.forecasted_price,
                "horizon_label": m.horizon_label,
            }
            for m in (doc.metadata for doc in docs)
        ]
        messages = self._build_messages(question, docs, eda_docs)

        payload = {
            "model": OLLAMA_MODEL,
            "messages": messages,
            "stream": True,
            "keep_alive": -1,
            "think": False,
            "options": {
                "temperature": OLLAMA_TEMPERATURE,
                "num_predict": OLLAMA_NUM_PREDICT,
                "num_ctx": 4096,
            },
        }

        logger.debug(
            "Streaming Ollama response for question: %r (%d forecast docs, %d EDA docs)",
            question[:120],
            len(docs),
            len(eda_docs),
        )

        # ── Running think-block stripper ──────────────────────────────────────
        # We accumulate a small lookahead buffer to detect split tags.
        # OPEN_TAG / CLOSE_TAG lengths determine how much we hold back.
        OPEN_TAG = "<think>"
        CLOSE_TAG = "</think>"
        # Max bytes we need to buffer to detect a partial tag at a boundary
        MAX_HOLD = max(len(OPEN_TAG), len(CLOSE_TAG)) - 1

        def _flush_visible(buf: str, in_think: bool) -> tuple[str, str, bool]:
            """Process *buf*, return (to_yield, remaining_buf, in_think)."""
            to_yield = ""
            while buf:
                if in_think:
                    idx = buf.find(CLOSE_TAG)
                    if idx == -1:
                        # closing tag not here yet — hold back MAX_HOLD chars
                        # in case the tag is split across the next chunk
                        hold = min(len(buf), MAX_HOLD)
                        buf = buf[len(buf) - hold:]
                        break
                    in_think = False
                    buf = buf[idx + len(CLOSE_TAG):]
                else:
                    idx = buf.find(OPEN_TAG)
                    if idx == -1:
                        # no opening tag — emit everything except the tail hold
                        hold = min(len(buf), MAX_HOLD)
                        to_yield += buf[:len(buf) - hold]
                        buf = buf[len(buf) - hold:]
                        break
                    to_yield += buf[:idx]
                    in_think = True
                    buf = buf[idx + len(OPEN_TAG):]
            return to_yield, buf, in_think

        try:
            in_think = False
            buf = ""

            with httpx.Client(timeout=OLLAMA_TIMEOUT_SECONDS) as client:
                with client.stream("POST", OLLAMA_URL, json=payload) as response:
                    response.raise_for_status()

                    for line in response.iter_lines():
                        if not line:
                            continue
                        try:
                            chunk = json.loads(line)
                        except json.JSONDecodeError:
                            continue

                        delta: str = chunk.get("message", {}).get("content", "")
                        if delta:
                            buf += delta
                            visible, buf, in_think = _flush_visible(buf, in_think)
                            if visible:
                                yield f"data: {json.dumps({'type': 'token', 'text': visible})}\n\n"

                        if chunk.get("done"):
                            break

            # Flush any remaining buffer content after stream ends
            if buf and not in_think:
                yield f"data: {json.dumps({'type': 'token', 'text': buf})}\n\n"

            yield f"data: {json.dumps({'type': 'done', 'sources': sources})}\n\n"

        except httpx.TimeoutException as exc:
            logger.error("Ollama stream timed out: %s", exc)
            yield f"data: {json.dumps({'type': 'error', 'text': 'The language model timed out. Please try again.'})}\n\n"
        except httpx.ConnectError as exc:
            logger.error("Ollama unreachable during stream: %s", exc)
            yield f"data: {json.dumps({'type': 'error', 'text': 'The LLM service is unavailable. Ensure Ollama is running on localhost:11434.'})}\n\n"
        except httpx.HTTPStatusError as exc:
            logger.error("Ollama HTTP error during stream: %s", exc)
            yield f"data: {json.dumps({'type': 'error', 'text': f'LLM service error (HTTP {exc.response.status_code}). Please try again.'})}\n\n"
        except Exception as exc:
            logger.error("Unexpected error during Ollama stream: %s", exc, exc_info=True)
            yield f"data: {json.dumps({'type': 'error', 'text': 'An unexpected error occurred.'})}\n\n"
